.PHONY: all
all:
	echo type make install
install:
	install sshd-wrapper.pl /usr/sbin/sshd-wrapper
	install ssh-wrapper.pl /usr/bin/ssh-wrapper
	@echo
	@echo add /usr/sbin/sshd-wrapper to your inetd configuration
